services:
  - type: web
    name: mgnrega-dashboard
    runtime: python
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn mgnrega_dashboard.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: MGNREGA_API_KEY
        sync: false