# Generated by Django 4.2 on 2025-10-24 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mgnregadata',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterUniqueTogether(
            name='mgnregadata',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='district',
            name='area',
        ),
        migrations.AddField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='district_code',
            field=models.CharField(default='UNKNOWN', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mgnregadata',
            name='average_days_per_household',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mgnregadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mgnregadata',
            name='material_expenditure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='mgnregadata',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mgnregadata',
            name='total_active_workers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mgnregadata',
            name='total_job_cards_issued',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mgnregadata',
            name='total_workers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mgnregadata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mgnregadata',
            name='wage_expenditure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='mgnregadata',
            name='works_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mgnregadata',
            name='works_in_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=100),
        ),
        migrations.AlterField(
            model_name='mgnregadata',
            name='employment_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mgnregadata',
            name='total_expenditure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='mgnregadata',
            name='total_work_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterUniqueTogether(
            name='mgnregadata',
            unique_together={('district', 'year', 'month')},
        ),
    ]
