# Generated by Django 4.2 on 2025-10-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0002_alter_district_options_alter_mgnregadata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_code',
            field=models.CharField(default='UNKNOWN', max_length=20, unique=True),
        ),
    ]
